import { Flex } from "@chakra-ui/react";
import type { NextPage } from "next";
import { Session } from "next-auth";
import { getSession } from "next-auth/react";
import Head from "next/head";
import { Hero } from "../components/molecules/Hero/Hero";
import { LandingBody } from "../components/organisms/LandingBody/LandingBody";
import { LandingFooter } from "../components/organisms/LandingFooter/LandingFooter";
import { TopBar } from "../components/organisms/TopBar/TopBar";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>SuperApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <Flex>
        <Hero />
      </Flex>
      <LandingBody />
      <LandingFooter />
    </div>
  );
};

export async function getServerSideProps(context: any) {
  const session = await getSession(context);

  if (session) {
    return {
      redirect: {
        destination: "/logged",
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
}

export default Home;
